import { type PortfolioItem } from "./PortfolioItem";

// Uses picsum.photos (seed = deterministic image, dimensions hint quality).
// Requires next.config.mjs: { protocol: "https", hostname: "picsum.photos" }
export const DUMMY_PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "p01",
    src: "https://picsum.photos/seed/bsi01/800/800",
    alt: "Brand identity for Arkana Cosmetics",
    aspectRatio: "1/1",
    title: "Arkana Cosmetics — Brand Identity",
    category: "Brand Design",
  },
  {
    id: "p02",
    src: "https://picsum.photos/seed/bsi02/600/800",
    alt: "Campaign visual for Danone Indonesia",
    aspectRatio: "3/4",
    title: "Danone — Ramadan Campaign",
    category: "Social Media",
  },
  {
    id: "p03",
    src: "https://picsum.photos/seed/bsi03/800/450",
    alt: "TVC production for Astra Honda Motor",
    aspectRatio: "16/9",
    title: "Honda BeAT — TVC 2025",
    category: "Video Production",
  },
  {
    id: "p04",
    src: "https://picsum.photos/seed/bsi04/640/800",
    alt: "Product photography for Wardah Beauty",
    aspectRatio: "4/5",
    title: "Wardah — Product Launch",
    category: "Photography",
  },
  {
    id: "p05",
    src: "https://picsum.photos/seed/bsi05/800/533",
    alt: "Corporate film for BRI",
    aspectRatio: "3/2",
    title: "BRI — Corporate Profile Film",
    category: "Video Production",
  },
  {
    id: "p06",
    src: "https://picsum.photos/seed/bsi06/533/800",
    alt: "Motion graphics for Tokopedia",
    aspectRatio: "2/3",
    title: "Tokopedia — Harbolnas Motion",
    category: "Motion Design",
  },
  {
    id: "p07",
    src: "https://picsum.photos/seed/bsi07/800/600",
    alt: "Advertising campaign for Indomie",
    aspectRatio: "4/3",
    title: "Indomie — Seleraku Campaign",
    category: "Campaign",
  },
  {
    id: "p08",
    src: "https://picsum.photos/seed/bsi08/600/800",
    alt: "Social media content for Gojek",
    aspectRatio: "3/4",
    title: "Gojek — Lebaran Content Pack",
    category: "Social Media",
  },
  {
    id: "p09",
    src: "https://picsum.photos/seed/bsi09/800/800",
    alt: "Logo & identity system for startup",
    aspectRatio: "1/1",
    title: "Kopi Kita — Rebranding",
    category: "Brand Design",
  },
  {
    id: "p10",
    src: "https://picsum.photos/seed/bsi10/640/800",
    alt: "Fashion photography editorial",
    aspectRatio: "4/5",
    title: "Batik Keris — Editorial Shoot",
    category: "Photography",
  },
  {
    id: "p11",
    src: "https://picsum.photos/seed/bsi11/800/450",
    alt: "International campaign for Singapore Tourism",
    aspectRatio: "16/9",
    title: "Singapore Tourism — Wanderlust 2025",
    category: "International",
  },
  {
    id: "p12",
    src: "https://picsum.photos/seed/bsi12/800/533",
    alt: "Short film documentary",
    aspectRatio: "3/2",
    title: "Tanah Air — Documentary Short",
    category: "Video Production",
  },
  {
    id: "p13",
    src: "https://picsum.photos/seed/bsi13/533/800",
    alt: "App UI/UX showcase for fintech",
    aspectRatio: "2/3",
    title: "PayLater — App Campaign",
    category: "Digital Marketing",
  },
  {
    id: "p14",
    src: "https://picsum.photos/seed/bsi14/600/800",
    alt: "Influencer content series",
    aspectRatio: "3/4",
    title: "Sariwangi — Creator Series",
    category: "Content",
  },
  {
    id: "p15",
    src: "https://picsum.photos/seed/bsi15/800/800",
    alt: "Event photography and documentation",
    aspectRatio: "1/1",
    title: "Jakarta Fashion Week — Coverage",
    category: "Photography",
  },
  {
    id: "p16",
    src: "https://picsum.photos/seed/bsi16/800/600",
    alt: "Product demo video for ASUS Indonesia",
    aspectRatio: "4/3",
    title: "ASUS ROG — Product Reveal",
    category: "Video Production",
  },
  {
    id: "p17",
    src: "https://picsum.photos/seed/bsi17/640/800",
    alt: "Brand visual identity for luxury hotel",
    aspectRatio: "4/5",
    title: "The Apurva — Visual Identity",
    category: "Brand Design",
  },
  {
    id: "p18",
    src: "https://picsum.photos/seed/bsi18/800/533",
    alt: "Commercial shoot for Pertamina",
    aspectRatio: "3/2",
    title: "Pertamina — Energi Nusantara",
    category: "Campaign",
  },
  {
    id: "p19",
    src: "https://picsum.photos/seed/bsi19/600/800",
    alt: "Social media reel for Shopee",
    aspectRatio: "3/4",
    title: "Shopee 12.12 — Reel Series",
    category: "Social Media",
  },
  {
    id: "p20",
    src: "https://picsum.photos/seed/bsi20/800/450",
    alt: "Live event broadcast visuals",
    aspectRatio: "16/9",
    title: "Synchronize Fest — Broadcast Pack",
    category: "Motion Design",
  },
  {
    id: "p21",
    src: "https://picsum.photos/seed/bsi21/800/600",
    alt: "Behind-the-scenes content for Lazada",
    aspectRatio: "4/3",
    title: "Lazada — BTS Creators Hub",
    category: "Content",
  },
  {
    id: "p22",
    src: "https://picsum.photos/seed/bsi22/533/800",
    alt: "International series for Tourism Malaysia",
    aspectRatio: "2/3",
    title: "Malaysia Truly Asia — Series",
    category: "International",
  },
  {
    id: "p23",
    src: "https://picsum.photos/seed/bsi23/800/533",
    alt: "Sports brand campaign visuals",
    aspectRatio: "3/2",
    title: "Specs Sport — Game On",
    category: "Campaign",
  },
  {
    id: "p24",
    src: "https://picsum.photos/seed/bsi24/800/800",
    alt: "Annual report photography for Telkom",
    aspectRatio: "1/1",
    title: "Telkom — Annual Report 2025",
    category: "Photography",
  },
];
